# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# in the templates via {{ site.myvariable }}.
title: Interagir 
email: gleisoncosta705@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Olá eu sou o gleison oliveira e neste blog quero poder com partilhar algumas   
  histórias de vida, conhecimento e poder conhecer pessoas incriveis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gleisoncosta89
github_username:  ggalfa

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
